### ISSUE TITLE
 v0.25.0: Installation fails

### ISSUE THREAD

**Issue by FlxAlbroscheit** [stimulus-use/stimulus-use#156] opened 2021-06-24 10:00 UTC
Calling a "npm install stimulus-use" fails when trying to install latest version 0.25.0. This seems to be related to "hotkeys-js" which is declared a peerDependency. Npm output:

```
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: hotkeys-js@undefined
npm WARN node_modules/hotkeys-js
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer hotkeys-js@">3" from stimulus-use@0.25.0
npm WARN node_modules/stimulus-use
npm WARN   stimulus-use@"*" from the root project
npm ERR! code ETARGET
npm ERR! notarget No matching version found for hotkeys-js@>3.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```
As one would expect, regular install of <= 0.24 works without troubles.

Node version: 14.16.0
Npm version: 7.11.2

**Comment by adrienpoly** [comment] 2021-06-24 10:34
Yes it looks like the installation is not happy when hotkeys-js is not installed within the project.

Using yarn on another project I am experiencing a different error at run time (install completes correctly)

I get a :  Uncaught SyntaxError: Invalid left-hand side in assignment

![Capture d’écran 2021-06-24 à 12 28 27 PM](https://user-images.githubusercontent.com/7847244/123248012-ba1e1680-d4e7-11eb-907c-329962fd35aa.jpg)

and it points to this

```js
enhanceController() {
        if (this.hotkeysOptions.filter) {
            !(function webpackMissingModule() { var e = new Error("Cannot find module 'hotkeys-js'"); e.code = 'MODULE_NOT_FOUND'; throw e; }()).filter = this.hotkeysOptions.filter;
        }
        const controllerDisconnect = this.controller.disconnect.bind(this.controller);
        const disconnect = () => {
            this.unbind();
            controllerDisconnect();
        };
        Object.assign(this.controller, { disconnect });
    }
```

Our goal was really to make this hotkeys-js package fully optional, looks like it is not the case yet!

poke @julianrubisch are you seeing something similar?

**Comment by julianrubisch** [comment] 2021-06-24 11:09
Uh no, though tbh I haven't tried yet.

Baffling that it would throw up at a peer dependency... I thought it should be treeshakable if one doesn't import `useHotkeys` 🤯

Apparently I've still not completely understood how bundlers work 🤦‍♂️

@marcoroth @ParamagicDev to the rescue? ⛑

**Comment by adrienpoly** [comment] 2021-06-24 11:19
| Apparently I've still not completely understood how bundlers work 🤦‍♂️

#metoo

**Comment by adrienpoly** [comment] 2021-06-24 12:09
### Some additionnal information

Installing hotkey-js AND **restating webpack-dev-server** was necessary on my side to run again the project.

I supposed tree-shaking was not working locally because we are in development mode. So I tried adding hotkeys-js as a devDependencies and push to a production environment but it failed (I am using webpacker 5).  

So it clearly looks like the tree-shaking is not working. 

is it required to have webpacker 6 (webpack 5) to have a better tree-shaking ?
Not sure how accurate is [agadoo](https://github.com/Rich-Harris/agadoo), I run it before each publish.

**Comment by julianrubisch** [comment] 2021-06-24 12:17
okay, so this is just me spitballing, because I've no idea how to set up microbundle to fix this, but what if we removed `useHotkeys` here:

https://github.com/stimulus-use/stimulus-use/blob/main/src/index.ts#L18

and instead somehow published it as a separate module?

**Comment by adrienpoly** [comment] 2021-06-24 12:20
what I will do as a hottie is to release a patch version with hotkeys as a dependency. Given that the package is only 2k gzip it looks like the best short term solution to me.

**Comment by FlxAlbroscheit** [comment] 2021-06-24 12:30
I had no time yet to investigate on this issue deeply, but in general it should be sufficient...
* ...to declare hotkeys-js a simple dependency (or, if you assume that hotkeys-js will already be a dependency of the parent project, a [peerDependenciesMeta](https://stackoverflow.com/a/66228639))
* ...and to let the bundler figure out whether to (not) import hotkeys-js, depending on whether { useHotkeys } is imported in the parent project. In case of using webpack for bundling, it may be recommended to mark the project explicitly as ["side effect free"](https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free)

Also, the agadoo package mentioned by adrienpoly has some [recommendations](https://github.com/Rich-Harris/agadoo#help-my-library-isnt-tree-shakeable-and-im-not-sure-why) for getting tree-shakability up and running.

**Comment by julianrubisch** [comment] 2021-06-24 12:33
sorry to be causing so much trouble and yes, I thought 

> let the bundler figure out whether to (not) import hotkeys-js, depending on whether { useHotkeys } is imported in the parent project.

this would be the job of the bundler...

**Comment by adrienpoly** [comment] 2021-06-24 12:53
@FlxAlbroscheit I published v0.25.1 with your  peerDependenciesMeta. Could you try that ?

**Comment by ParamagicDev** [comment] 2021-06-24 14:57
So i think theres a couple issues at play here:

the main package exported by stimulus-use is a UMD package and not a `module`

Modules have better tree-shaking and side-effect detection. My best guess is Webpack may actually be selecting the UMD version and not the module version. UMD is not tree-shakeable as far as im aware since its usually served from a CDN.

https://github.com/stimulus-use/stimulus-use/blob/c91a6b96ef71e9abf5a3940826588aa52e025055/package.json#L5

https://github.com/stimulus-use/stimulus-use/blob/c91a6b96ef71e9abf5a3940826588aa52e025055/package.json#L15

https://webpack.js.org/guides/ecma-script-modules/#flagging-modules-as-esm

https://github.com/developit/microbundle#usage-with-typemodule-in-packagejson

Let me submit a PR and see if it helps resolve some of these issues.

**Comment by adrienpoly** [comment] 2021-06-25 06:16
Thanks @ParamagicDev I released v0.25.3 with your suggestions and it works MUCH better!

@FlxAlbroscheit if you could confirm that it is working for you too with NPM (I used yarn)

**Comment by ParamagicDev** [comment] 2021-06-25 06:22
@adrienpoly As a cool side-effect, there is now a bundle export analysis on Bundlephobia!!

https://bundlephobia.com/package/stimulus-use@0.25.2

^ 0.25.2 without export analysis

https://bundlephobia.com/package/stimulus-use@0.25.3

^ 0.25.3 with export analysis so you can see how big each module is 🥳

**Comment by evenreven** [comment] 2021-06-27 18:15
I'm on 0.25.3 and I can't get it to work. I don't have hotkeys-js installed (and have no real intention to).

NOTE: I'm not using webpack(er), I'm using vite_rails, the Rails integration for ViteJS. On dev it uses esbuild for bundling. It gives me this message: 

```
Pre-bundling dependencies:
  stimulus
  stimulus-vite-helpers
  stimulus-use
  js-cookie
  vanilla-lazyload
  (...and 2 more)
(this will be run only when your dependencies or config have changed)
 > node_modules/stimulus-use/dist/use-hotkeys/use-hotkeys.js:1:20: error: Could not resolve "hotkeys-js" (mark it as external to exclude it from the bundle)
    1 │ import hotkeys from 'hotkeys-js';
      ╵                     ~~~~~~~~~~~~

error when starting dev server:
Error: Build failed with 1 error:
node_modules/stimulus-use/dist/use-hotkeys/use-hotkeys.js:1:20: error: Could not resolve "hotkeys-js" (mark it as external to exclude it from the bundle)
    at failureErrorWithLog (/var/home/myuser/.local/dev/node_modules/esbuild/lib/main.js:1449:15)
    at /var/home/myuser/.local/dev/node_modules/esbuild/lib/main.js:1131:28
    at runOnEndCallbacks (/var/home/myuser/.local/dev/node_modules/esbuild/lib/main.js:921:63)
    at buildResponseToResult (/var/home/myuser/.local/dev/node_modules/esbuild/lib/main.js:1129:7)
    at /var/home/myuser/.local/dev/node_modules/esbuild/lib/main.js:1236:14
    at /var/home/myuser/.local/dev/node_modules/esbuild/lib/main.js:609:9
    at handleIncomingPacket (/var/home/myuser/.local/dev/node_modules/esbuild/lib/main.js:706:9)
    at Socket.readFromStdout (/var/home/myuser/.local/dev/node_modules/esbuild/lib/main.js:576:7)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
exit status 1
``` 

I suppose Vite won't include hotkeys-js in my bundle (even if I install) it if tree-shaking works, and so it won't hurt to add it to package.json. Vite uses Rollup, which (historically, at least) has been even better than Webpack at tree-shaking. But it feels a bit... wrong. I don't want to put stuff in package.json that I don't mean to use.

Is this an esbuild problem or a stimulus-use problem, you think?

**Comment by ParamagicDev** [comment] 2021-06-27 18:34
@evenreven I think this is part of the prebundle process where Vite will try to optimize dependencies. Usually this includes all node_modules, but since hotkeys-js is not in node_modules, it tries to prebundle it for you. Im not 100% which option it would be, but its either the `rollupOptions` where you would mark it as external, or `optimizeDeps.exclude`

## Optimize Deps

https://vitejs.dev/config/#optimizedeps-exclude

## Rollup External Option

https://vitejs.dev/config/#build-rollupoptions

https://rollupjs.org/guide/en/#external

And if you do that, it wont attempt to fetch and optimize the package...i believe.

**Comment by evenreven** [comment] 2021-06-27 18:37
Thanks, that was fast! I'll try this. 

So, just to confirm... 0.25.3 currently works with webpack without installing hotkeys-js?

**Comment by ParamagicDev** [comment] 2021-06-27 18:49
As far as I understand, @adrienpoly confirmed this. I havent had the chance to try it out, but it _should_ work without installing at this point. This may be an issue that Vite has to solve in the future where it checks the packages `peerDependencies` and marks them as external, but thats not an easy problem to solve.

**Comment by evenreven** [comment] 2021-06-27 19:16
This is tricky. Vite really doesn't like the structure of this, it seems. Thing is, there are code paths that depend on hotkeys, and even though I'm not using them directly, esbuild wants them to be there. I don't think vite will even be happy with this.

`optimizeDeps.exclude` works in the sense that `bin/vite dev` manages to start now instead of just failing outright, but esbuild fails once I try to load an actual page. 

I now get this message in the browser (Vite displays errors in modals, not just in terminal output):

```
[plugin:vite:import-analysis] Failed to resolve import "hotkeys-js" from "node_modules/.vite/stimulus-use.js?v=98c63e93". Does the file exist?
```

Haven't tried Rollup settings, but I'm pretty sure Rollup is only used for production builds. Getting a correct production build is of course great, but I need to develop as well. ;)

For now, I'll just yarn add hotkeys-js so I can go on with my day, but I'll be interested to dive deeper into this later. Thanks so far!

**Comment by ParamagicDev** [comment] 2021-06-27 19:27
Well, there is a significantly less optimal fix that could be possible here to totally avoid this. You could leave it to the user to bind the 3 imported functions:

https://github.com/stimulus-use/stimulus-use/blob/f397d35fbc75a990819b21d7a6997349b3a75d32/src/use-hotkeys/use-hotkeys.ts#L2

and then have stimulus-use attempt to find the 3 imports on the `window` something like this:

```js
// set by the user of the library.

import hotkeys, { KeyHandler, HotkeysEvent } from 'hotkeys-js'/

window.stimulusUse = {
  hotkeys: {
    hotkeys,
    KeyHandler,
    HotkeysEvent
  }
}
```

And then basically Stimulus-use would call something like: `window.stimulusUse.hotkeys.hotkeys` to access the `hotkeys` API. its not optimal, but is another way of making it `hotkeys-js` a true peerDependency. The issue is that bundlers are in a weird space right now and all behave slightly differently.

**Comment by adrienpoly** [comment] 2021-06-27 21:48
> As far as I understand, @adrienpoly confirmed this. I havent had the chance to try it out, but it _should_ work without installing at this point. This may be an issue that Vite has to solve in the future where it checks the packages `peerDependencies` and marks them as external, but thats not an easy problem to solve.

yes I confirm that it is working fine for me with webpacker both in dev and production

**Comment by adrienpoly** [comment] 2021-06-27 21:52
> For now, I'll just yarn add hotkeys-js so I can go on with my day, but I'll be interested to dive deeper into this later. Thanks so far!

@evenreven if I understand correctly it is working in production but not in dev right now. If you add hotkeys-js to your dev dependencies does it somehow solve your issue? or you need it as a real dependency?

One solution could be to add hotkey as a dev dependency of Stimulus-Use

**Comment by evenreven** [comment] 2021-06-28 04:15
Why would I make it a dev dependency? Just to make sure the file is there, yet make sure it's not in the production build? I can of course try this for the sake of experimenting, but it's a worse solution than including it in the project and then letting Rollup tree shake it back out. If I have to install it, it would be great if I could actually just use it if I change my mind. Dev dependency would be the worst of both worlds, imo. It would clutter up package.json, yet the sections wouldn't even make sense anymore. 

Maybe dev dependency would be a good solution for stimulus-use, though. I've never developed a library, so not sure what would be a good idea there.

Apart from this, Vite is great. I dislike webpack quite strongly, so it's great that there's a viable alternative that's a lot closer to the Rails Way than webpack is (i.e. sensible defaults).

**Comment by Intrepidd** [comment] 2021-06-28 07:36
Hi there,

not sure what's going on, but on my end I now get this error with 0.25.3 : 

```
ERROR in ./node_modules/stimulus-use/dist/use-hotkeys/use-hotkeys.js 1:0-33
Module not found: Error: Can't resolve 'hotkeys-js' in '/home/runner/work/ecotable/ecotable/node_modules/stimulus-use/dist/use-hotkeys'
resolve 'hotkeys-js' in '/home/runner/work/ecotable/ecotable/node_modules/stimulus-use/dist/use-hotkeys'
  Parsed request is a module
  using description file: /home/runner/work/ecotable/ecotable/node_modules/stimulus-use/package.json (relative path: ./dist/use-hotkeys)
```

**Comment by evenreven** [comment] 2021-06-28 07:42
@Intrepidd Is this with Webpacker? 

Although the discussion above has to do with Vite and not webpack, the short-term solution is still the same: `yarn add hotkeys-js`, and then your bundler is supposed to tree-shake so that hotkeys-js won't go into your production site unless you want to (i.e. import it in one of your controllers).

**Comment by Intrepidd** [comment] 2021-06-28 08:32
It is with webpacker and the fix works, thanks :)

**Comment by FlxAlbroscheit** [comment] 2021-06-29 09:16
Hey there :) I'm back in office and had a chance to test your latest release. So far, thanks for your quick response and contribution!

Unfortunately, on building my app which imports stimulus-use (but NOT use-hotkeys) I get the same error as Intrepidd above: "hotkeys-js missing". Of course it's missing, as hotkeys-js is declared a devDependency ;) Turning it into a dependency does, however, not change the core problem that hotkeys-js still becomes part of the final bundle (both in dev- and prod-mode). This is weird, as the current configuration in package.json seems to be fully okay and modular :/ Maybe I have to check my webpack config...

Currently, the only thing that indeed works is to import stimulus-use modules via underscore.js/lodash-like import syntax:
`import {useClickOutside} from 'stimulus-use/dist/use-click-outside';`

Not nice, but doing well so far.

**Comment by adrienpoly** [comment] 2021-07-14 19:54
v0.25.4 includes hotkeys-js as a dependency (9603eba) and should fix all installation issues. 
I have tested and treeshaking works perfectly for me when I don't use `useHotkey` I don't have the package in my final bundle.

closing it for now let me know if there are still issues on you side

**Closed by adrienpoly** 2021-07-14 19:54 UTC
Labels: bug

**Comment by adrienpoly** [comment] 2021-07-15 06:25
@all-contributors please add @FlxAlbroscheit to bug
